[package]
name = "arca-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clean-path = "0.2.1"
path-slash = "0.2.1"
radix_trie = "0.2.1"
