[package]
name = "arca"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "Various utilities used in my crates"
repository = "https://github.com/arcanis/arca-rs.git"

[dependencies]
clean-path = "0.2.1"
path-slash = "0.2.1"
radix_trie = "0.2.1"
